
'use client';
import Link from 'next/link';
import {useState} from 'react';
import {Menu,X,MapPin,Heart,ShoppingBag,UserRound,Bell,Search,ChevronDown,Gift,Truck} from 'lucide-react';
import {siteConfig} from '@/lib/config';
import {useStore} from './StoreProvider';
import {categories} from '@/data/categories';
import {occasions} from '@/data/occasions';

export default function Header(){
 const[open,setOpen]=useState(false); const[mega,setMega]=useState<string|null>(null); const{cartCount,wishlist}=useStore();
 const nav=[['Gifts','gifts'],['Birthday','/birthday-gifts'],['Anniversary','/anniversary-gifts'],['Flowers','/flowers'],['Cakes','/cakes'],['Personalised','/personalised-gifts'],['Hampers','/gift-hampers'],['Plants','/plants'],['Chocolates','/chocolates'],['Occasions','occasions'],['Corporate Gifts','/corporate-gifts']];
 return <>
 <div className="hidden border-b border-berry/10 bg-cream text-xs text-slate-600 lg:block"><div className="container-shell flex h-9 items-center justify-between"><div className="flex items-center gap-2"><MapPin size={14} className="text-rose"/><span>Deliver to</span><button className="font-black text-berry">{siteConfig.defaultCity} 500049</button></div><div className="flex items-center gap-5"><Link href="/track-order">Track Order</Link><Link href="/reminders">Gift Reminder</Link><Link href="/corporate-gifts">Corporate Gifting</Link><Link href="/contact">Help</Link></div></div></div>
 <header className="sticky top-0 z-50 border-b border-[#eee0e5] bg-white/95 backdrop-blur-xl">
  <div className="container-shell flex min-h-[72px] items-center gap-3 lg:gap-6">
   <button aria-label="Open menu" onClick={()=>setOpen(true)} className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[#eadde2] lg:hidden"><Menu size={21}/></button>
   <Link href="/" className="flex shrink-0 items-center gap-2 font-black tracking-tight text-berry"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-berry text-xl text-white shadow-lg shadow-berry/20"><Gift/></span><span className="hidden text-xl sm:inline">{siteConfig.name}</span></Link>
   <form action="/gifts" className="relative order-last w-full lg:order-none lg:flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={19}/><input name="q" placeholder="Search gifts, flowers, cakes, occasions..." className="h-12 w-full rounded-full border border-[#e9dce1] bg-[#fffafc] pl-11 pr-4 text-sm transition focus:border-rose focus:bg-white focus:ring-4 focus:ring-rose/10"/></form>
   <div className="ml-auto hidden shrink-0 items-center gap-1.5 lg:flex"><Link href="/reminders" className="grid h-11 w-11 place-items-center rounded-full hover:bg-blush" title="Reminders"><Bell size={20}/></Link><Link href="/wishlist" className="relative grid h-11 w-11 place-items-center rounded-full hover:bg-blush" title="Wishlist"><Heart size={20}/>{wishlist.length>0&&<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-rose px-1 text-[10px] font-black text-white">{wishlist.length}</span>}</Link><Link href="/cart" className="relative grid h-11 w-11 place-items-center rounded-full hover:bg-blush" title="Cart"><ShoppingBag size={20}/>{cartCount>0&&<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-berry px-1 text-[10px] font-black text-white">{cartCount}</span>}</Link><Link href="/account" className="grid h-11 w-11 place-items-center rounded-full hover:bg-blush" title="Account"><UserRound size={20}/></Link></div>
   <Link href="/cart" className="relative grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[#eadde2] lg:hidden"><ShoppingBag size={20}/>{cartCount>0&&<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-berry px-1 text-[10px] font-black text-white">{cartCount}</span>}</Link>
  </div>
  <div className="container-shell flex items-center gap-2 pb-3 text-xs text-slate-600 lg:hidden"><MapPin size={15} className="text-rose"/>Delivering to <button className="font-black text-berry">{siteConfig.defaultCity} 500049</button></div>
  <nav className="hidden border-t border-[#f4e9ec] lg:block"><div className="container-shell flex h-12 items-center justify-center gap-7">{nav.map(([label,href])=>{const isMega=href==='gifts'||href==='occasions';return isMega?<button key={label} onMouseEnter={()=>setMega(href)} onFocus={()=>setMega(href)} className="inline-flex h-full items-center gap-1 text-sm font-bold text-slate-700 hover:text-berry">{label}<ChevronDown size={14}/></button>:<Link key={label} href={href} className="text-sm font-bold text-slate-700 hover:text-berry">{label}</Link>})}</div></nav>
  {mega&&<div onMouseLeave={()=>setMega(null)} className="absolute left-0 right-0 top-full hidden border-t border-[#eee0e5] bg-white shadow-2xl lg:block"><div className="container-shell grid grid-cols-4 gap-10 py-8">{mega==='gifts'?<><div><h3 className="font-black text-berry">Gift Categories</h3><div className="mt-4 grid gap-2">{categories.slice(0,6).map(c=><Link onClick={()=>setMega(null)} key={c.slug} href={`/gifts/${c.slug}`} className="text-sm text-slate-600 hover:text-berry">{c.name}</Link>)}</div></div><div><h3 className="font-black text-berry">Gifts For</h3><div className="mt-4 grid gap-2">{['Her','Him','Kids','Mom','Dad','Friends'].map(x=><Link onClick={()=>setMega(null)} key={x} href={`/gifts-for/${x.toLowerCase()}`} className="text-sm text-slate-600 hover:text-berry">{x}</Link>)}</div></div><div><h3 className="font-black text-berry">Shop by Price</h3><div className="mt-4 grid gap-2">{['Under ₹500','₹500–₹999','₹1,000–₹1,999','Premium Gifts'].map(x=><Link onClick={()=>setMega(null)} key={x} href="/gifts" className="text-sm text-slate-600 hover:text-berry">{x}</Link>)}</div></div><div className="rounded-[1.6rem] bg-blush p-5"><span className="text-xs font-black uppercase tracking-widest text-rose">Trending</span><h3 className="mt-2 text-xl font-black text-berry">Personalised gifts that feel truly theirs.</h3><Link onClick={()=>setMega(null)} href="/personalised-gifts" className="mt-5 inline-flex items-center font-black text-berry">Explore <span className="ml-2">→</span></Link></div></>:<><div className="col-span-3 grid grid-cols-3 gap-6">{occasions.map(o=><Link onClick={()=>setMega(null)} key={o.slug} href={`/occasion/${o.slug}`} className="rounded-xl px-3 py-2 text-sm font-bold text-slate-700 hover:bg-blush hover:text-berry">{o.emoji} {o.name}</Link>)}</div><div className="rounded-[1.6rem] bg-berry p-6 text-white"><Truck className="text-gold"/><h3 className="mt-4 text-xl font-black">Need it soon?</h3><p className="mt-2 text-sm text-white/75">Explore selected same-day and express delivery gifts.</p><Link href="/same-day-gifts" onClick={()=>setMega(null)} className="mt-5 inline-block font-black text-gold">Shop fast gifts →</Link></div></>}</div></div>}
 </header>
 {open&&<div className="fixed inset-0 z-[80] bg-ink/45 lg:hidden" onClick={()=>setOpen(false)}><aside className="absolute left-0 top-0 h-full w-[90%] max-w-sm overflow-y-auto bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><Link href="/" onClick={()=>setOpen(false)} className="flex items-center gap-2 text-xl font-black text-berry"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-berry text-white"><Gift size={20}/></span>{siteConfig.name}</Link><button onClick={()=>setOpen(false)} className="grid h-11 w-11 place-items-center rounded-full border"><X/></button></div><div className="mt-7 grid gap-1">{[['Shop Gifts','/gifts'],['Occasions','/occasion/birthday'],['Gifts For','/gifts-for/her'],['Flowers','/flowers'],['Cakes','/cakes'],['Personalised','/personalised-gifts'],['Hampers','/gift-hampers'],['Plants','/plants'],['Offers','/offers'],['Track Order','/track-order'],['Gift Reminders','/reminders'],['Account','/account']].map(([n,h])=><Link onClick={()=>setOpen(false)} key={n} href={h} className="rounded-2xl px-4 py-3.5 font-bold text-slate-700 hover:bg-blush hover:text-berry">{n}</Link>)}</div><div className="mt-6 grid grid-cols-2 gap-3"><Link href="/wishlist" onClick={()=>setOpen(false)} className="btn-secondary"><Heart size={17} className="mr-2"/>Wishlist</Link><Link href="/cart" onClick={()=>setOpen(false)} className="btn-primary"><ShoppingBag size={17} className="mr-2"/>Cart</Link></div></aside></div>}
 </>
}
